[package]
name = "verus_stub"
version = "0.1.0"
edition.workspace = true

[dependencies]

verus_macro_stub = { workspace = true, optional = true}

[features]
default = ["dep:verus_macro_stub"]
disable = []

[lints]
workspace = true
